[package]
name = "graphql_derive"
version = "0.1.0"
authors = ["Tiziano Santoro <tiziano88@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
serde_derive_internals = "0.19"
